import { data, metricDefs } from "../mocks/mock-data.js";
import { initArchitectureGraph } from "./architecture-graph.js";

        function metricClass(k) { k = k.toLowerCase(); if (k.includes('speedup')) return 'm-speed'; if (k.includes('accepted') || k.includes('acceptance')) return 'm-accept'; if (k.includes('rejected')) return 'm-reject'; if (k.includes('fallback')) return 'm-fallback'; if (k.includes('tokens/sec')) return 'm-tps'; if (k.includes('latency')) return 'm-lat'; return 'm-token' }
        function metricsFor(obj, kind) { const keys = kind === 'low' ? ['latency_seconds', 'decode_tokens_per_sec', 'total_tokens_per_sec', 'prompt_tokens', 'completion_tokens', 'total_tokens', 'prefill_ms', 'decode_ms', 'memory_gb', 'draft_block_size', 'cycle_count', 'accepted_draft_tokens', 'rejected_draft_tokens', 'fallback_tokens', 'acceptance_rate', 'verification_mode', 'correctness_note', 'speedup'] : ['latency_seconds', 'decode_tokens_per_sec', 'total_tokens_per_sec', 'prompt_tokens', 'completion_tokens', 'total_tokens', 'prefill_ms', 'decode_ms', 'memory_gb', 'low_tier_accepted_tokens', 'low_tier_rejected_tokens', 'low_tier_fallback_tokens', 'high_tier_accepted_tokens', 'high_tier_rejected_tokens', 'high_tier_fallback_tokens', 'low_tier_acceptance_rate', 'high_tier_acceptance_rate', 'verification_mode', 'correctness_note', 'speedup']; return keys.map(k => ({ label: k.replaceAll('_', ' '), value: obj[k], cls: metricClass(k) })) }
        function renderMetrics(id, arr) { document.getElementById(id).innerHTML = arr.map(m => `<div class="metric ${m.cls}"><span>${m.label}</span><b>${m.value}</b></div>`).join('') }
        function setStatus(id, t) { const el = document.getElementById(id); el.textContent = t; el.className = 'status ' + (t === 'RUNNING' ? 'running' : t === 'DONE' ? 'done' : '') }
        function progress(wrap, fill, dur) { return new Promise(res => { const w = document.getElementById(wrap), f = document.getElementById(fill); w.style.display = 'block'; f.style.width = '0%'; let start; function step(ts) { if (!start) start = ts; const p = Math.min((ts - start) / dur, 1); f.style.width = (p * 100) + '%'; if (p < 1) requestAnimationFrame(step); else setTimeout(() => { w.style.display = 'none'; res() }, 180) } requestAnimationFrame(step) }) }
        function markSteps(id, index) { [...document.getElementById(id).children].forEach((s, i) => { s.className = 'step ' + (i < index ? 'done' : i === index ? 'active' : '') }) }
        function resetSteps(id) { [...document.getElementById(id).children].forEach(s => s.className = 'step') }
        async function startLow() { document.getElementById('ltStart').disabled = true; document.getElementById('ltCompare').style.display = 'none'; resetSteps('ltSteps'); setStatus('ltBaseStatus', 'RUNNING'); markSteps('ltSteps', 0); await progress('ltBaseProg', 'ltBaseFill', 1300); document.getElementById('ltBaseResp').textContent = data.low.baseline.response; renderMetrics('ltBaseMetrics', metricsFor(data.low.baseline, 'low')); setStatus('ltBaseStatus', 'DONE'); markSteps('ltSteps', 1); await new Promise(r => setTimeout(r, 500)); setStatus('ltArchStatus', 'RUNNING'); markSteps('ltSteps', 2); await progress('ltArchProg', 'ltArchFill', 1500); document.getElementById('ltArchResp').textContent = data.low.arch.response; renderMetrics('ltArchMetrics', metricsFor(data.low.arch, 'low')); setStatus('ltArchStatus', 'DONE'); markSteps('ltSteps', 3); await new Promise(r => setTimeout(r, 500)); markSteps('ltSteps', 4); const b = data.low.baseline, a = data.low.arch; document.getElementById('ltCompareBody').innerHTML = `D-Flash Low-tier reached <b>${a.speedup}</b> speedup over the E2B baseline. Latency changed from <b>${b.latency_seconds}s</b> to <b>${a.latency_seconds}s</b>, while decode throughput increased from <b>${b.decode_tokens_per_sec}</b> to <b>${a.decode_tokens_per_sec}</b> tok/s. Accepted draft tokens: <b>${a.accepted_draft_tokens}</b>, rejected: <b>${a.rejected_draft_tokens}</b>, fallback: <b>${a.fallback_tokens}</b>.`; document.getElementById('ltCompare').style.display = 'block'; markSteps('ltSteps', 5); document.getElementById('ltStart').disabled = false }
        function resetLow() { resetSteps('ltSteps');['ltBaseMetrics', 'ltArchMetrics'].forEach(id => document.getElementById(id).innerHTML = ''); document.getElementById('ltBaseResp').textContent = 'Waiting for baseline run...'; document.getElementById('ltArchResp').textContent = 'Waiting for D-Flash run...'; setStatus('ltBaseStatus', 'IDLE'); setStatus('ltArchStatus', 'IDLE'); document.getElementById('ltCompare').style.display = 'none' }
        async function startFull() { document.getElementById('fullStart').disabled = true; document.getElementById('fullCompare').style.display = 'none'; resetSteps('fullSteps'); setStatus('fullBaseStatus', 'RUNNING'); markSteps('fullSteps', 0); await progress('fullBaseProg', 'fullBaseFill', 1600); document.getElementById('fullBaseResp').textContent = data.full.baseline.response; renderMetrics('fullBaseMetrics', metricsFor(data.full.baseline, 'full')); setStatus('fullBaseStatus', 'DONE'); markSteps('fullSteps', 1); await new Promise(r => setTimeout(r, 500)); setStatus('fullArchStatus', 'RUNNING'); markSteps('fullSteps', 2); await progress('fullArchProg', 'fullArchFill', 1800); document.getElementById('fullArchResp').textContent = data.full.arch.response; renderMetrics('fullArchMetrics', metricsFor(data.full.arch, 'full')); setStatus('fullArchStatus', 'DONE'); markSteps('fullSteps', 3); await new Promise(r => setTimeout(r, 500)); markSteps('fullSteps', 4); const b = data.full.baseline, a = data.full.arch; document.getElementById('fullCompareBody').innerHTML = `Full HTFSD reached <b>${a.speedup}</b> end-to-end speedup over the E4B baseline. Latency changed from <b>${b.latency_seconds}s</b> to <b>${a.latency_seconds}s</b>, while decode throughput increased from <b>${b.decode_tokens_per_sec}</b> to <b>${a.decode_tokens_per_sec}</b> tok/s. Low-tier acceptance: <b>${a.low_tier_acceptance_rate}</b>; high-tier acceptance: <b>${a.high_tier_acceptance_rate}</b>.`; document.getElementById('fullCompare').style.display = 'block'; markSteps('fullSteps', 5); document.getElementById('fullStart').disabled = false }
        function resetFull() { resetSteps('fullSteps');['fullBaseMetrics', 'fullArchMetrics'].forEach(id => document.getElementById(id).innerHTML = ''); document.getElementById('fullBaseResp').textContent = 'Waiting for E4B baseline run...'; document.getElementById('fullArchResp').textContent = 'Waiting for Full HTFSD run...'; setStatus('fullBaseStatus', 'IDLE'); setStatus('fullArchStatus', 'IDLE'); document.getElementById('fullCompare').style.display = 'none' }
        document.getElementById('ltStart').addEventListener('click', startLow); document.getElementById('ltReset').addEventListener('click', resetLow); document.getElementById('fullStart').addEventListener('click', startFull); document.getElementById('fullReset').addEventListener('click', resetFull); document.getElementById('metricDefs').innerHTML = metricDefs.map((d, i) => { const metricColors = ["var(--yellow)", "var(--cyan)", "var(--green)", "var(--paper)", "var(--silver)", "#fff", "var(--orange)", "var(--hot)", "var(--purple)", "var(--cyan)", "var(--yellow)", "var(--green)", "var(--red)", "var(--orange)", "var(--purple)", "var(--hot)", "var(--silver)", "#fff"]; const whiteText = [6, 7, 8, 12, 13, 14, 15].includes(i); return `<div class="def-card" style="background:${metricColors[i % metricColors.length]};${whiteText ? 'color:white;' : ''}"><h3>${d[0]}</h3><p>${d[1]}</p></div>` }).join('');
        initArchitectureGraph();

